package dealership.api.model;

import java.math.BigDecimal;

/**
 * Data transfer object representing a global summary for the owner dashboard.
 * <p>
 * This class aggregates high-level metrics related to sales activity,
 * repair activity, and current vehicle stock. It is typically used to
 * display summary information in owner-facing reporting or dashboard views.
 * </p>
 */
public class OwnerSummaryRow {

    private int salesCount;
    private BigDecimal salesTotal;

    private int repairsCount;
    private BigDecimal repairsTotal;

    private int unsoldStockCount;

    /**
     * Default constructor.
     * <p>
     * Required for object instantiation and framework deserialization.
     * </p>
     */
    public OwnerSummaryRow() {}

    /**
     * Creates a new summary instance with all aggregated values.
     *
     * @param salesCount total number of sales
     * @param salesTotal total amount generated by sales
     * @param repairsCount total number of completed repairs
     * @param repairsTotal total amount generated by repairs
     * @param unsoldStockCount number of vehicles that are not sold
     */
    public OwnerSummaryRow(
            int salesCount,
            BigDecimal salesTotal,
            int repairsCount,
            BigDecimal repairsTotal,
            int unsoldStockCount
    ) {
        this.salesCount = salesCount;
        this.salesTotal = salesTotal;
        this.repairsCount = repairsCount;
        this.repairsTotal = repairsTotal;
        this.unsoldStockCount = unsoldStockCount;
    }

    /**
     * Returns the total number of sales.
     *
     * @return the sales count
     */
    public int getSalesCount() {
        return salesCount;
    }

    /**
     * Sets the total number of sales.
     *
     * @param salesCount the sales count to set
     */
    public void setSalesCount(int salesCount) {
        this.salesCount = salesCount;
    }

    /**
     * Returns the total sales amount.
     *
     * @return the total sales amount
     */
    public BigDecimal getSalesTotal() {
        return salesTotal;
    }

    /**
     * Sets the total sales amount.
     *
     * @param salesTotal the total sales amount to set
     */
    public void setSalesTotal(BigDecimal salesTotal) {
        this.salesTotal = salesTotal;
    }

    /**
     * Returns the total number of completed repairs.
     *
     * @return the repairs count
     */
    public int getRepairsCount() {
        return repairsCount;
    }

    /**
     * Sets the total number of completed repairs.
     *
     * @param repairsCount the repairs count to set
     */
    public void setRepairsCount(int repairsCount) {
        this.repairsCount = repairsCount;
    }

    /**
     * Returns the total repair revenue amount.
     *
     * @return the total repair revenue
     */
    public BigDecimal getRepairsTotal() {
        return repairsTotal;
    }

    /**
     * Sets the total repair revenue amount.
     *
     * @param repairsTotal the total repair revenue to set
     */
    public void setRepairsTotal(BigDecimal repairsTotal) {
        this.repairsTotal = repairsTotal;
    }

    /**
     * Returns the number of vehicles that are currently not sold.
     *
     * @return the unsold stock count
     */
    public int getUnsoldStockCount() {
        return unsoldStockCount;
    }

    /**
     * Sets the number of vehicles that are currently not sold.
     *
     * @param unsoldStockCount the unsold stock count to set
     */
    public void setUnsoldStockCount(int unsoldStockCount) {
        this.unsoldStockCount = unsoldStockCount;
    }
}
